### ISSUE TITLE
Possible Compilation Error With latest rgbds

### ISSUE THREAD

**Issue by wildcat2083** [dannye/pokered-gbc#7]
I have used this repository several times and now when running "make" the repo will not build, the pokered project builds but I get build errors on wram.asm and it closes the make process

**Comment by dannye** [comment]
I'll update it eventually. For now, compile with rgbds v0.2.5
